stages:
  - build
  - push
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  IMAGE_REGISTRY: registry.gitlab.com/cyclops4100006/nextiamg

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"

# Build NextiaMG
build_nextiamg:
  stage: build
  script:
    - docker compose -f nextiamg_full/docker-compose.deploy.yml build --no-cache frontend backend
  tags:
    - docker
  only:
    - main

# Push to GitLab Registry
push_nextiamg:
  stage: push
  script:
    - docker push $IMAGE_REGISTRY/nextiamg_frontend
    - docker push $IMAGE_REGISTRY/nextiamg_backend
  tags:
    - docker
  only:
    - main
  needs:
    - build_nextiamg

# Deploy NextiaMG
deploy_nextiamg:
  stage: deploy
  script:
    - echo "Deploying NextiaMG..."
    - docker compose -f docker-compose.deploy.yml pull
    - docker compose -f docker-compose.deploy.yml up -d --remove-orphans
    - docker compose -f /docker-compose.deploy.yml ps
  tags:
    - docker
  only:
    - main
  needs:
    - push_nextiamg
