stages:
  - build

# Build NextiaMG
build_nextiamg:
  stage: build
  script:
    - docker compose -f nextiamg_full/docker-compose.yml build --no-cache frontend backend
  tags:
    - docker
  only:
    - main

