version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - graphdb
    volumes:
      - shared-data:/backend/api/api/dbFiles/DataLayer

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - graphdb

  intents2workflows:
    build:
      context: ./backend/Modules/IntentSpecification2WorkflowGenerator
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - graphdb
    volumes:
      - shared-data:/backend/api/api/dbFiles/DataLayer

  intents_anticipation:
    build:
      context: ./backend/Modules/IntentAnticipation
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
    environment:
      - INTENTS2WORKFLOWS_URL=http://intents2workflows:8000
      - GRAPHDB_URL=http://graphdb:7200
    depends_on:
      - graphdb

  dq_rule_discovery:
    image: aniolupc/dq-discovery:latest
    ports:
      - "5050:5000"

  graphdb:
    build:
      context: .
      dockerfile: Dockerfile.graphdb
    ports:
      - "7200:7200"


volumes:
  shared-data: