version: '3.8'

services:
  backend:
    ports:
      - "3000:3000"
    volumes:
      - shared-data:/backend/api/api/dbFiles/DataLayer
    image: registry.gitlab.com/cyclops4100006/nextiamg/nextiamg_backend
    depends_on:
      - graphdb
    networks:
      - long-term-storage_default
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:3000/actuator/health || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      - LTS_ENDPOINT=http://minio:9000
      - LTS_ACCESKEY=minioadmin
      - LTS_SECRETKEY=minioadmin123
      - LTS_BUCKET=long-term-storage
      - LTS_CYCLOPSLTS=MinIO


  frontend:
    ports:
      - "9000:9000"
    image: registry.gitlab.com/cyclops4100006/nextiamg/nextiamg_frontend
    environment:
      - BUILD_MODE=build
    depends_on:
      backend:
        condition: service_healthy
      graphdb:
        condition: service_started


  graphdb:
    build:
      context: .
      dockerfile: Dockerfile.graphdb
    ports:
      - "7200:7200"


volumes:
  shared-data:

networks:
  long-term-storage_default:
    external: true