version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - graphdb
    volumes:
      - shared-data:/backend/api/api/dbFiles/DataLayer
    networks:
      - long-term-storage_default
    environment:
      - LTS_ENDPOINT=http://minio:9200
      - LTS_ACCESKEY=minioadmin
      - LTS_SECRETKEY=minioadmin123
      - LTS_BUCKET=long-term-storage
      - LTS_CYCLOPSLTS=MinIO


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - graphdb

  intents2workflows:
    build:
      context: ./backend/Modules/IntentSpecification2WorkflowGenerator
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - graphdb
    volumes:
      - shared-data:/backend/api/api/dbFiles/DataLayer

  intents_anticipation:
    build:
      context: ./backend/Modules/IntentAnticipation
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
    environment:
      - INTENTS2WORKFLOWS_URL=http://intents2workflows:8000
      - GRAPHDB_URL=http://graphdb:7200
    depends_on:
      - graphdb

  graphdb:
    build:
      context: .
      dockerfile: Dockerfile.graphdb
    ports:
      - "7200:7200"


volumes:
  shared-data:

networks:
    long-term-storage_default:
        external: true